import LittlewoodInverse

#print axioms LittlewoodInverse.aspect_log_gain
#print axioms LittlewoodInverse.boundary_log_ratio_aspect
#print axioms LittlewoodInverse.aspect_boundary_budget
#print axioms LittlewoodInverse.affineImage_comp
#print axioms LittlewoodInverse.terminal_affine
#print axioms LittlewoodInverse.terminal_nonempty
#print axioms LittlewoodInverse.AssemblyLeafFamily.leaf_subset
#print axioms LittlewoodInverse.AssemblyLeafFamily.leaf_nonempty
#print axioms LittlewoodInverse.AssemblyLeafFamily.sum_card
#print axioms LittlewoodInverse.AssemblyLeafFamily.leaf_norm_le
#print axioms LittlewoodInverse.AssemblyLeafFamily.leaf_count_le
#print axioms LittlewoodInverse.AssemblyLeafFamily.threshold_count_mul_pow_le
#print axioms LittlewoodInverse.AssemblyLeafFamily.small_leaf_mass_le
#print axioms LittlewoodInverse.AssemblyLeafFamily.large_leaf_count_le
#print axioms LittlewoodInverse.AssemblyLeafFamily.small_leaf_mass_log_bound
#print axioms LittlewoodInverse.assembly_has_terminal_leaves
#print axioms LittlewoodInverse.small_leaf_envelope_isLittleO
#print axioms LittlewoodInverse.eventually_small_leaf_envelope
#print axioms LittlewoodInverse.eventually_log_le_two_log_mul
#print axioms LittlewoodInverse.assembly_inverse_of_terminal
#print axioms LittlewoodInverse.fourierPolynomial_continuous
#print axioms LittlewoodInverse.fourierPolynomial_integrable
#print axioms LittlewoodInverse.littlewoodNorm_nonneg
#print axioms LittlewoodInverse.littlewoodNorm_empty
#print axioms LittlewoodInverse.littlewoodNorm_singleton
#print axioms LittlewoodInverse.additiveEnergy_pos
#print axioms LittlewoodInverse.card_pow_four_le_sumset_mul_energy
#print axioms LittlewoodInverse.BinomialLimit.cast_choose_eq_prod
#print axioms LittlewoodInverse.BinomialLimit.tendsto_choose_affine_div_pow
#print axioms LittlewoodInverse.boundaryShift_injective
#print axioms LittlewoodInverse.mem_boundaryTranslate
#print axioms LittlewoodInverse.boundaryValue_formula
#print axioms LittlewoodInverse.boundaryValue_cases
#print axioms LittlewoodInverse.boundaryValue_ne_zero_iff
#print axioms LittlewoodInverse.boundaryMass_le
#print axioms LittlewoodInverse.boundary_nonzero
#print axioms LittlewoodInverse.boundaryMass_pos
#print axioms LittlewoodInverse.boundary_sum
#print axioms LittlewoodInverse.boundaryMass_eq_sum_sq
#print axioms LittlewoodInverse.boundaryPolynomial_continuous
#print axioms LittlewoodInverse.boundaryPolynomial_difference
#print axioms LittlewoodInverse.boundaryPolynomial_zero
#print axioms LittlewoodInverse.blockCellIndex_injective
#print axioms LittlewoodInverse.blockInflation_eq_image
#print axioms LittlewoodInverse.blockInflation_card
#print axioms LittlewoodInverse.fourier_nat_mul
#print axioms LittlewoodInverse.blockInflation_fourier
#print axioms LittlewoodInverse.block_boundary_identity
#print axioms LittlewoodInverse.boundary_dual_integrable
#print axioms LittlewoodInverse.mixedCharacter_continuous
#print axioms LittlewoodInverse.mixedCharacter_norm
#print axioms LittlewoodInverse.integral_mixedCharacter_pair
#print axioms LittlewoodInverse.integral_mixed_term_pair
#print axioms LittlewoodInverse.mixedPolynomial_continuous
#print axioms LittlewoodInverse.mixedPolynomial_pair
#print axioms LittlewoodInverse.mixedPolynomial_second_moment
#print axioms LittlewoodInverse.boundaryPolynomial_eq_mixed
#print axioms LittlewoodInverse.boundaryNorm_nonneg
#print axioms LittlewoodInverse.boundary_second_moment
#print axioms LittlewoodInverse.boundaryNorm_le_sqrt_mass
#print axioms LittlewoodInverse.mixedCoefficient_norm_le
#print axioms LittlewoodInverse.one_le_boundaryNorm
#print axioms LittlewoodInverse.boundaryVertical_continuous
#print axioms LittlewoodInverse.boundaryPolynomial_cyclic
#print axioms LittlewoodInverse.boundaryQ_continuous
#print axioms LittlewoodInverse.boundaryQ_nonneg
#print axioms LittlewoodInverse.boundaryQ_sq
#print axioms LittlewoodInverse.integral_boundaryQ_sq
#print axioms LittlewoodInverse.integral_boundaryQ_le
#print axioms LittlewoodInverse.boundaryPhase_sub_one_le
#print axioms LittlewoodInverse.cyclicPolynomial_integral_norm_le
#print axioms LittlewoodInverse.boundaryW_zero
#print axioms LittlewoodInverse.integral_boundaryW_zero
#print axioms LittlewoodInverse.boundary_freezing
#print axioms LittlewoodInverse.boundaryW_nonneg
#print axioms LittlewoodInverse.boundaryW_expansion
#print axioms LittlewoodInverse.q_smul_div_shift
#print axioms LittlewoodInverse.boundary_frequency_div_shift
#print axioms LittlewoodInverse.boundaryW_inflation_identity
#print axioms LittlewoodInverse.norm_one_sub_fourier_one
#print axioms LittlewoodInverse.sum_zmod_eq_sum_range
#print axioms LittlewoodInverse.residueNormAverage_nonneg
#print axioms LittlewoodInverse.residueNormAverage_continuous
#print axioms LittlewoodInverse.littlewoodNorm_eq_interval
#print axioms LittlewoodInverse.residueNormAverage_integral
#print axioms LittlewoodInverse.fourierPolynomial_neg_argument
#print axioms LittlewoodInverse.residueNormAverage_even
#print axioms LittlewoodInverse.residueNormAverage_half_integral
#print axioms LittlewoodInverse.two_mul_integral_residue_le
#print axioms LittlewoodInverse.boundaryW_continuous_s
#print axioms LittlewoodInverse.boundary_pointwise_lower
#print axioms LittlewoodInverse.circle_integral_eq_unit_interval
#print axioms LittlewoodInverse.boundaryW_zero_periodic
#print axioms LittlewoodInverse.boundaryQ_periodic
#print axioms LittlewoodInverse.boundary_arc_lower
#print axioms LittlewoodInverse.mem_cellResidues
#print axioms LittlewoodInverse.cell_membership_constant
#print axioms LittlewoodInverse.boundary_heights_bracket
#print axioms LittlewoodInverse.le_nextSlabHeight
#print axioms LittlewoodInverse.nextSlabHeight_le_of_mem
#print axioms LittlewoodInverse.nextSlabHeight_no_between
#print axioms LittlewoodInverse.cellSlab_subset
#print axioms LittlewoodInverse.cellSlab_disjoint
#print axioms LittlewoodInverse.cellSlabs_cover
#print axioms LittlewoodInverse.blockInflation_biUnion
#print axioms LittlewoodInverse.blockInflation_disjoint
#print axioms LittlewoodInverse.blockInflation_product_interval
#print axioms LittlewoodInverse.inflated_cellSlab
#print axioms LittlewoodInverse.Majority.abs_majority
#print axioms LittlewoodInverse.Majority.abs_sign
#print axioms LittlewoodInverse.Majority.abs_walsh
#print axioms LittlewoodInverse.Majority.bernoulliWeight_nonneg
#print axioms LittlewoodInverse.Majority.sum_bernoulliWeight
#print axioms LittlewoodInverse.Majority.bernoulliWeight_eq_product
#print axioms LittlewoodInverse.Majority.polynomial_eq_expectation
#print axioms LittlewoodInverse.Majority.polynomial_abs_le_one
#print axioms LittlewoodInverse.Majority.majority_compl
#print axioms LittlewoodInverse.Majority.sign_compl
#print axioms LittlewoodInverse.Majority.walsh_compl
#print axioms LittlewoodInverse.Majority.coefficient_even_eq_zero
#print axioms LittlewoodInverse.Majority.abs_coefficient_le_one
#print axioms LittlewoodInverse.Majority.coefficient_mass_le
#print axioms LittlewoodInverse.Majority.coefficient_singleton
#print axioms LittlewoodInverse.Majority.centralBinom_squared_lower
#print axioms LittlewoodInverse.Majority.normalized_centralBinom_squared_lower
#print axioms LittlewoodInverse.Majority.linear_amplitude_nonneg
#print axioms LittlewoodInverse.Majority.linear_amplitude_squared_lower
#print axioms LittlewoodInverse.Majority.linear_amplitude_ge_four_mul
#print axioms LittlewoodInverse.sine_reciprocal_error
#print axioms LittlewoodInverse.boundary_pointwise_asymptotic_error
#print axioms LittlewoodInverse.residueNormAverage_le_card
#print axioms LittlewoodInverse.boundary_asymptotic_cut_error
#print axioms LittlewoodInverse.boundary_asymptotic_explicit
#print axioms LittlewoodInverse.boundary_norm_asymptotic
#print axioms LittlewoodInverse.uniform_boundary_extraction
#print axioms LittlewoodInverse.boundary_log_ratio_lower
#print axioms LittlewoodInverse.constant_boundary_budget_of_log
#print axioms LittlewoodInverse.constant_boundary_budget
#print axioms LittlewoodInverse.BoundedCompositions.card_composition
#print axioms LittlewoodInverse.BoundedCompositions.sum_threshold
#print axioms LittlewoodInverse.BoundedCompositions.threshold_le_iff
#print axioms LittlewoodInverse.BoundedCompositions.threshold_sum_le
#print axioms LittlewoodInverse.BoundedCompositions.bounded_eq_inf_compl
#print axioms LittlewoodInverse.BoundedCompositions.mem_inf_bad
#print axioms LittlewoodInverse.BoundedCompositions.card_inf_bad_of_le
#print axioms LittlewoodInverse.BoundedCompositions.card_inf_bad_of_gt
#print axioms LittlewoodInverse.BoundedCompositions.bounded_card_inclusion_exclusion
#print axioms LittlewoodInverse.BoundedCompositions.bounded_card_binomial_sum
#print axioms LittlewoodInverse.BoundedCompositions.bounded_card_eq_grid
#print axioms LittlewoodInverse.BoundedCompositions.interval_relationCount_eq_bounded
#print axioms LittlewoodInverse.BoundedCompositions.interval_relationCount_binomial
#print axioms LittlewoodInverse.residueHeight_injective
#print axioms LittlewoodInverse.arithmeticSlab_card
#print axioms LittlewoodInverse.arithmeticSlab_sum_subset
#print axioms LittlewoodInverse.carry_sumset_card
#print axioms LittlewoodInverse.carry_doubling
#print axioms LittlewoodInverse.absoluteValueApproximant_degree
#print axioms LittlewoodInverse.absoluteValueApproximant_error
#print axioms LittlewoodInverse.exists_even_absoluteValue_approximation
#print axioms LittlewoodInverse.freiman_norm_transport
#print axioms LittlewoodInverse.freiman_cardinality_order_norm_transport
#print axioms LittlewoodInverse.freiman_model_logarithmic_bound
#print axioms LittlewoodInverse.MomentCertificate.coefficientBound_valid
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_5
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_6
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_7
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_8
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_9
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_10
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_11
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_12
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_13
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_14
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_15
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_16
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_17
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_18
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_19
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_20
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_21
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_22
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_23
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_24
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_25
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_26
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_27
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_28
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_29
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_30
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_31
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_32
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_33
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_34
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_35
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_36
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_37
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_38
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_39
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_40
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_41
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_42
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_43
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_44
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_45
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_46
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_47
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_48
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_49
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_50
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_51
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_52
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_53
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_54
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_55
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_56
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_57
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_58
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_59
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_60
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_61
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_62
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_63
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_64
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_65
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_66
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_67
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_68
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_69
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_70
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_71
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_72
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_73
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_74
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_75
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_76
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_77
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_78
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_79
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_80
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_81
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_82
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_83
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_84
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_85
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_86
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_87
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_88
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_89
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_90
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_91
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_92
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_93
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_94
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_95
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_96
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_97
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_98
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_99
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_100
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_101
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_102
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_103
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_104
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_105
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_106
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_107
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_108
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_109
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_110
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_111
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_112
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_113
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_114
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_115
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_116
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_117
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_118
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_119
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_120
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_121
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_122
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_123
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_124
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_125
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_126
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_127
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_128
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_129
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_130
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_131
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_132
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_133
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_134
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_135
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_136
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_137
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_138
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_139
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_140
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_141
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_142
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_143
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_144
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_145
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_146
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_147
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_148
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_149
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_150
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_151
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_152
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_153
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_154
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_155
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_156
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_157
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_158
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_159
#print axioms LittlewoodInverse.MomentCertificate.coefficient_le_160
#print axioms LittlewoodInverse.mem_boundaryHeights
#print axioms LittlewoodInverse.boundaryValue_zero_of_height_not_mem
#print axioms LittlewoodInverse.boundaryValue_zero_of_not_mem_carrier
#print axioms LittlewoodInverse.boundaryRowNorm_nonneg
#print axioms LittlewoodInverse.boundaryRow_zero_of_not_mem
#print axioms LittlewoodInverse.boundary_sum_rows
#print axioms LittlewoodInverse.boundaryPolynomial_eq_rows
#print axioms LittlewoodInverse.boundaryRow_eq_coefficient
#print axioms LittlewoodInverse.boundaryRow_norm_le_circleIntegral
#print axioms LittlewoodInverse.boundaryNorm_eq_iterated
#print axioms LittlewoodInverse.boundaryRowNorm_le
#print axioms LittlewoodInverse.one_le_boundaryRowNorm
#print axioms LittlewoodInverse.boundaryPolynomial_eq_sorted
#print axioms LittlewoodInverse.exists_boundary_log_bound
#print axioms LittlewoodInverse.exists_boundary_height_bound
#print axioms LittlewoodInverse.cyclicPolynomial_cellResidues
#print axioms LittlewoodInverse.boundaryRow_sum_telescope
#print axioms LittlewoodInverse.cellResidues_norm_le_boundary
#print axioms LittlewoodInverse.compactCharacter_zero
#print axioms LittlewoodInverse.norm_compactCharacter
#print axioms LittlewoodInverse.continuous_compactCharacter
#print axioms LittlewoodInverse.compactCharacter_add
#print axioms LittlewoodInverse.compactCharacter_neg
#print axioms LittlewoodInverse.compactCharacter_mul
#print axioms LittlewoodInverse.compact_integrable
#print axioms LittlewoodInverse.integral_compactCharacter
#print axioms LittlewoodInverse.integral_compactCharacter_mul_conj
#print axioms LittlewoodInverse.continuous_compactPolynomial
#print axioms LittlewoodInverse.integral_compactPolynomial
#print axioms LittlewoodInverse.integral_compact_term_pair
#print axioms LittlewoodInverse.integral_compactPolynomial_pair
#print axioms LittlewoodInverse.integral_compactPolynomial_norm_sq
#print axioms LittlewoodInverse.integral_compact_indexed_norm_sq
#print axioms LittlewoodInverse.compactPolynomial_sq
#print axioms LittlewoodInverse.integral_compactPolynomial_norm_four
#print axioms LittlewoodInverse.discrete_freiman_norm_transport
#print axioms LittlewoodInverse.discrete_freiman_transport
#print axioms LittlewoodInverse.discrete_freiman_cardinality_order_norm_transport
#print axioms LittlewoodInverse.discrete_model_family_norm_transport
#print axioms LittlewoodInverse.compactCharacter_sum
#print axioms LittlewoodInverse.compactSet_polynomial_pow
#print axioms LittlewoodInverse.compactSet_norm_even_pow_expansion
#print axioms LittlewoodInverse.integral_compactSet_even_moment
#print axioms LittlewoodInverse.compact_freiman_relationCount
#print axioms LittlewoodInverse.compact_freiman_integral_even_moment
#print axioms LittlewoodInverse.integral_compactSet_norm_four
#print axioms LittlewoodInverse.compact_spectral_hereditary_energy
#print axioms LittlewoodInverse.discrete_spectral_hereditary_energy
#print axioms LittlewoodInverse.compact_sidon_fourth_term_le
#print axioms LittlewoodInverse.compact_sidon_fourth_moment
#print axioms LittlewoodInverse.compact_sidon_zero_sum
#print axioms LittlewoodInverse.compact_sidon_square_moment_zero
#print axioms LittlewoodInverse.compactPolynomial_split_constant
#print axioms LittlewoodInverse.compact_coefficient_second_split
#print axioms LittlewoodInverse.compact_sidon_normalized_twentieth
#print axioms LittlewoodInverse.compact_additiveSidon_image_sub
#print axioms LittlewoodInverse.compact_sidon_twentieth
#print axioms LittlewoodInverse.compact_sidon_constant_one
#print axioms LittlewoodInverse.compact_dual_sidon_constant_one
#print axioms LittlewoodInverse.norm_polynomial_approximation_integral
#print axioms LittlewoodInverse.integral_norm_transport_of_moments
#print axioms LittlewoodInverse.compactSet_norm_le_card
#print axioms LittlewoodInverse.compact_freiman_norm_transport
#print axioms LittlewoodInverse.compact_freiman_cardinality_order_norm_transport
#print axioms LittlewoodInverse.macroscopic_energy_corollary
#print axioms LittlewoodInverse.exceptional_perturbation_corollary
#print axioms LittlewoodInverse.canonical_coset_lift
#print axioms LittlewoodInverse.cyclic_coset_lift
#print axioms LittlewoodInverse.mem_arithmeticSlab_iff
#print axioms LittlewoodInverse.signed_indicator_lift
#print axioms LittlewoodInverse.signed_progression_lift
#print axioms LittlewoodInverse.covering_intersection
#print axioms LittlewoodInverse.energy_from_cover
#print axioms LittlewoodInverse.almostCover_freiman_map
#print axioms LittlewoodInverse.almostCover_freiman_iff
#print axioms LittlewoodInverse.almostCover_mono
#print axioms LittlewoodInverse.assembly_glue_covers
#print axioms LittlewoodInverse.mem_cyclicProgressionCoset
#print axioms LittlewoodInverse.cyclic_subgroup_modulus
#print axioms LittlewoodInverse.cyclic_coset_normal_form
#print axioms LittlewoodInverse.integral_cyclicMeasure
#print axioms LittlewoodInverse.cyclicCharacter_zero
#print axioms LittlewoodInverse.norm_cyclicCharacter
#print axioms LittlewoodInverse.cyclicCharacter_add
#print axioms LittlewoodInverse.integral_cyclicCharacter
#print axioms LittlewoodInverse.cyclic_integrable
#print axioms LittlewoodInverse.cyclicCharacter_neg
#print axioms LittlewoodInverse.integral_cyclicCharacter_mul_conj
#print axioms LittlewoodInverse.integral_cyclicPolynomial
#print axioms LittlewoodInverse.integral_cyclic_term_pair
#print axioms LittlewoodInverse.integral_cyclicPolynomial_pair
#print axioms LittlewoodInverse.integral_cyclicPolynomial_norm_sq
#print axioms LittlewoodInverse.integral_cyclic_indexed_norm_sq
#print axioms LittlewoodInverse.cyclicPolynomial_sq
#print axioms LittlewoodInverse.integral_cyclicPolynomial_norm_four
#print axioms LittlewoodInverse.sidon_fourth_term_le
#print axioms LittlewoodInverse.cyclic_sidon_fourth_moment
#print axioms LittlewoodInverse.sidon_zero_sum
#print axioms LittlewoodInverse.cyclic_sidon_square_moment_zero
#print axioms LittlewoodInverse.cyclicPolynomial_split_constant
#print axioms LittlewoodInverse.cyclic_coefficient_second_split
#print axioms LittlewoodInverse.cyclic_sidon_normalized_twentieth
#print axioms LittlewoodInverse.additiveSidon_image_sub
#print axioms LittlewoodInverse.cyclic_sidon_twentieth
#print axioms LittlewoodInverse.integral_cyclicSet_norm_four
#print axioms LittlewoodInverse.cyclic_spectral_hereditary_energy
#print axioms LittlewoodInverse.cyclicCoefficient_norm_le_integral
#print axioms LittlewoodInverse.one_le_cyclicLittlewoodNorm
#print axioms LittlewoodInverse.cyclicLittlewoodNorm_nonneg
#print axioms LittlewoodInverse.cyclicLittlewoodNorm_le_sqrt_card
#print axioms LittlewoodInverse.dampedTest_norm_le
#print axioms LittlewoodInverse.dampingTail_memLp
#print axioms LittlewoodInverse.dampingTail_support
#print axioms LittlewoodInverse.circlePairing_norm_le_littlewoodNorm
#print axioms LittlewoodInverse.dampedTest_lower_bound
#print axioms LittlewoodInverse.dense_blocks_cover
#print axioms LittlewoodInverse.Majority.GoodSet.mono
#print axioms LittlewoodInverse.Majority.dense_good_sets
#print axioms LittlewoodInverse.Majority.dense_mixed_correlations
#print axioms LittlewoodInverse.fourier_nat_pow
#print axioms LittlewoodInverse.intervalPolynomial_eq_geom_sum
#print axioms LittlewoodInverse.norm_fourier_sub_one
#print axioms LittlewoodInverse.intervalPolynomial_norm_mul_sin
#print axioms LittlewoodInverse.intervalPolynomial_norm_eq_sin_div
#print axioms LittlewoodInverse.normalized_intervalPolynomial_eq_sinc
#print axioms LittlewoodInverse.rationalCircleCast_coe
#print axioms LittlewoodInverse.rationalCircleCast_injective
#print axioms LittlewoodInverse.discrete_characters_separate
#print axioms LittlewoodInverse.discreteEvaluation_apply
#print axioms LittlewoodInverse.discreteEvaluation_injective
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_4
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_6
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_8
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_10
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_12
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_14
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_16
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_18
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_20
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_22
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_24
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_26
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_28
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_30
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_32
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_34
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_36
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_38
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_40
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_42
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_44
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_46
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_48
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_50
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_52
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_54
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_56
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_58
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_60
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_62
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_64
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_66
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_68
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_70
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_72
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_74
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_76
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_78
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_80
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_82
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_84
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_86
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_88
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_90
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_92
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_94
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_96
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_98
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_100
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_102
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_104
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_106
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_108
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_110
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_112
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_114
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_116
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_118
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_120
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_122
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_124
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_126
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_128
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_130
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_132
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_134
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_136
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_138
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_140
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_142
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_144
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_146
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_148
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_150
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_152
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_154
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_156
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_158
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_160
#print axioms LittlewoodInverse.MomentCertificate.sincMoment_162
#print axioms LittlewoodInverse.intervalDifferenceCount_eq
#print axioms LittlewoodInverse.fejerKernel_continuous
#print axioms LittlewoodInverse.fejerKernel_nonneg
#print axioms LittlewoodInverse.integral_fejerKernel
#print axioms LittlewoodInverse.norm_sq_fourierPolynomial_eq_indexed
#print axioms LittlewoodInverse.circleFourierCoeff_indexedFourierSum
#print axioms LittlewoodInverse.circleFourierCoeff_fejerKernel
#print axioms LittlewoodInverse.circleFourierCoeff_const_mul
#print axioms LittlewoodInverse.circleFourierCoeff_sub
#print axioms LittlewoodInverse.valleePoussinKernel_continuous
#print axioms LittlewoodInverse.circleFourierCoeff_valleePoussinKernel
#print axioms LittlewoodInverse.valleePoussinKernel_reproduces
#print axioms LittlewoodInverse.valleePoussinKernel_support
#print axioms LittlewoodInverse.integral_norm_valleePoussinKernel_le
#print axioms LittlewoodInverse.fibre_disjoint
#print axioms LittlewoodInverse.fourier_character_add
#print axioms LittlewoodInverse.fourier_mul_index
#print axioms LittlewoodInverse.fourierPolynomial_affine
#print axioms LittlewoodInverse.fourierPolynomial_fibreUnion
#print axioms LittlewoodInverse.q_smul_cyclicShift
#print axioms LittlewoodInverse.fourier_cyclicShift
#print axioms LittlewoodInverse.fibre_cyclic_expansion
#print axioms LittlewoodInverse.circle_integral_zsmul
#print axioms LittlewoodInverse.pilp_norm_twentieth
#print axioms LittlewoodInverse.fibreNormVector_continuous
#print axioms LittlewoodInverse.fibreNormVector_pointwise
#print axioms LittlewoodInverse.fibreNormVector_integral_coordinate
#print axioms LittlewoodInverse.cyclicTranslate_average_continuous
#print axioms LittlewoodInverse.cyclicTranslate_average_integral
#print axioms LittlewoodInverse.actual_fibre_twentieth_budget
#print axioms LittlewoodInverse.finiteFourierSum_continuous
#print axioms LittlewoodInverse.circleFourierCoeff_finiteFourierSum
#print axioms LittlewoodInverse.continuous_eq_of_circleFourierCoeff_eq
#print axioms LittlewoodInverse.valleePoussinKernel_eq_finiteFourierSum
#print axioms LittlewoodInverse.fourier_eval_sub
#print axioms LittlewoodInverse.integral_finiteFourierSum_sub_mul
#print axioms LittlewoodInverse.fourierPhase_measurable
#print axioms LittlewoodInverse.norm_fourierPhase_le_one
#print axioms LittlewoodInverse.fourierPhase_memLp_top
#print axioms LittlewoodInverse.fourierPhase_integrable
#print axioms LittlewoodInverse.fourierPolynomial_mul_star_phase
#print axioms LittlewoodInverse.circlePairing_fourierPhase
#print axioms LittlewoodInverse.finiteBandCertificate_continuous
#print axioms LittlewoodInverse.finiteBandCertificate_eq_convolution
#print axioms LittlewoodInverse.norm_finiteBandCertificate_le_one
#print axioms LittlewoodInverse.finiteBandCertificate_support
#print axioms LittlewoodInverse.circlePairing_finiteBandCertificate
#print axioms LittlewoodInverse.finite_band_certificate
#print axioms LittlewoodInverse.FiniteSetPartition.part_subset
#print axioms LittlewoodInverse.FiniteSetPartition.sum_card
#print axioms LittlewoodInverse.finite_partition_glue_covers
#print axioms LittlewoodInverse.bounded_partition_almost_cover
#print axioms LittlewoodInverse.FirstLevelUniform.momentEnvelope_nonneg
#print axioms LittlewoodInverse.FirstLevelUniform.normalizedMoment_le_envelope
#print axioms LittlewoodInverse.FirstLevelUniform.momentEnvelope_le_one
#print axioms LittlewoodInverse.FirstLevelUniform.tendsto_momentEnvelope
#print axioms LittlewoodInverse.FirstLevelUniform.summable_weighted_envelope
#print axioms LittlewoodInverse.FirstLevelUniform.tendsto_weighted_envelope
#print axioms LittlewoodInverse.FirstLevelUniform.normalized_series_le_envelope
#print axioms LittlewoodInverse.FirstLevelUniform.first_level_uniform
#print axioms LittlewoodInverse.continuous_circle_integrable
#print axioms LittlewoodInverse.integral_fourier
#print axioms LittlewoodInverse.integral_fourier_mul_conj
#print axioms LittlewoodInverse.circlePairing_fourierPolynomial
#print axioms LittlewoodInverse.circlePairing_fourierPolynomial_of_subset
#print axioms LittlewoodInverse.integral_norm_sq_fourierPolynomial
#print axioms LittlewoodInverse.integral_norm_pow_four_fourierPolynomial
#print axioms LittlewoodInverse.freiman_sumset_card
#print axioms LittlewoodInverse.freiman_energy
#print axioms LittlewoodInverse.high_order_freiman_exact
#print axioms LittlewoodInverse.freiman_fin_sum_iff
#print axioms LittlewoodInverse.freiman_relationCount
#print axioms LittlewoodInverse.freiman_integral_even_moment
#print axioms LittlewoodInverse.geometric_bounds_to_logarithmic
#print axioms LittlewoodInverse.affine_injective
#print axioms LittlewoodInverse.affine_card
#print axioms LittlewoodInverse.affine_nonempty
#print axioms LittlewoodInverse.affine_freiman_two
#print axioms LittlewoodInverse.affine_energy
#print axioms LittlewoodInverse.affine_sumset_card
#print axioms LittlewoodInverse.BackgroundExternal.zmodAddEquiv_apply_eq
#print axioms LittlewoodInverse.BackgroundExternal.finiteAlgebraNorm_indicator
#print axioms LittlewoodInverse.BackgroundExternal.green_sanders_cyclic_cosets
#print axioms LittlewoodInverse.BackgroundExternal.green_sanders_cyclic
#print axioms LittlewoodInverse.almostCover_of_hereditary
#print axioms LittlewoodInverse.initialPrefix_card
#print axioms LittlewoodInverse.initialPrefix_isInitialSegment
#print axioms LittlewoodInverse.boundaryNorm_single_cell
#print axioms LittlewoodInverse.interval_littlewoodNorm_asymptotic
#print axioms LittlewoodInverse.dirichlet_l1_asymptotic
#print axioms LittlewoodInverse.IntervalCoefficients.geometric_power_coefficient
#print axioms LittlewoodInverse.IntervalCoefficients.interval_relationCount_eq_coefficient
#print axioms LittlewoodInverse.IntervalCoefficients.relationCount_le_coefficient
#print axioms LittlewoodInverse.IntervalEnergy.pairSumCount_eq_interval
#print axioms LittlewoodInverse.IntervalEnergy.pairSumCount_lower
#print axioms LittlewoodInverse.IntervalEnergy.pairSumCount_upper
#print axioms LittlewoodInverse.IntervalEnergy.sum_integerInterval
#print axioms LittlewoodInverse.IntervalEnergy.energy_eq_sum_pairSumCount
#print axioms LittlewoodInverse.IntervalEnergy.energy_eq_two_square_sums
#print axioms LittlewoodInverse.IntervalEnergy.energy_eq_square_sum
#print axioms LittlewoodInverse.IntervalEnergy.square_sum_identity
#print axioms LittlewoodInverse.IntervalEnergy.three_mul_interval_energy
#print axioms LittlewoodInverse.IntervalEnergy.interval_energy_real
#print axioms LittlewoodInverse.IntervalEnergy.additiveEnergy_le_interval
#print axioms LittlewoodInverse.IntervalEnergy.three_mul_energy_le
#print axioms LittlewoodInverse.IntervalEnergy.energy_max_real
#print axioms LittlewoodInverse.IntervalEnergy.normalized_fourth_moment_eq
#print axioms LittlewoodInverse.IntervalEnergy.normalized_fourth_moment_le
#print axioms LittlewoodInverse.IntervalEnergy.normalized_fourth_moment_uniform
#print axioms LittlewoodInverse.IntervalMoments.signedSum_eq
#print axioms LittlewoodInverse.IntervalMoments.signedCoordinate_strictMono
#print axioms LittlewoodInverse.IntervalMoments.signedSum_strictMono
#print axioms LittlewoodInverse.IntervalMoments.gridDecode_injective
#print axioms LittlewoodInverse.IntervalMoments.relationCount_eq_zero_fiber
#print axioms LittlewoodInverse.IntervalMoments.relationCount_le_middle
#print axioms LittlewoodInverse.IntervalMoments.interval_signedSum
#print axioms LittlewoodInverse.IntervalMoments.interval_signedSum_zero_iff
#print axioms LittlewoodInverse.IntervalMoments.interval_relationCount_eq_middle
#print axioms LittlewoodInverse.IntervalMoments.relationCount_le_interval
#print axioms LittlewoodInverse.IntervalMoments.even_moment_le_interval
#print axioms LittlewoodInverse.littlewoodNorm_eq_two_half
#print axioms LittlewoodInverse.intervalPolynomial_norm_le_inv
#print axioms LittlewoodInverse.interval_littlewoodNorm_le_log
#print axioms LittlewoodInverse.DenseBlocks.label_injective
#print axioms LittlewoodInverse.list_floor_error
#print axioms LittlewoodInverse.bounded_floor_carry
#print axioms LittlewoodInverse.Landau.b_sq_wallis
#print axioms LittlewoodInverse.Landau.b_sq_eq_wallis_inv
#print axioms LittlewoodInverse.Landau.b_sq_lower
#print axioms LittlewoodInverse.Landau.b_sq_upper
#print axioms LittlewoodInverse.Landau.sum_b_sq_lower
#print axioms LittlewoodInverse.Landau.sum_b_sq_upper_succ
#print axioms LittlewoodInverse.Landau.sum_b_sq_upper
#print axioms LittlewoodInverse.Landau.sum_b_sq_log_error
#print axioms LittlewoodInverse.Landau.b_le_inv_sqrt
#print axioms LittlewoodInverse.Landau.b_sq_mul_le_one
#print axioms LittlewoodInverse.Landau.b_le_inv_sqrt_succ
#print axioms LittlewoodInverse.Landau.b_tendsto_zero
#print axioms LittlewoodInverse.Landau.norm_weighted_sum_le
#print axioms LittlewoodInverse.Landau.geometric_sum_bound
#print axioms LittlewoodInverse.Landau.partialSum_eq_eval
#print axioms LittlewoodInverse.Landau.partial_converges
#print axioms LittlewoodInverse.Landau.partialSum_tail
#print axioms LittlewoodInverse.Landau.norm_partialSum_tail
#print axioms LittlewoodInverse.Landau.boundary_tail_bound
#print axioms LittlewoodInverse.Landau.summable_norm_powerSum
#print axioms LittlewoodInverse.Landau.powerSum_square
#print axioms LittlewoodInverse.Landau.boundary_square
#print axioms LittlewoodInverse.Landau.boundary_norm
#print axioms LittlewoodInverse.Landau.boundary_ratio
#print axioms LittlewoodInverse.Landau.quotient_phase_error
#print axioms LittlewoodInverse.Landau.b_zero
#print axioms LittlewoodInverse.Landau.b_pos
#print axioms LittlewoodInverse.Landau.b_recurrence
#print axioms LittlewoodInverse.Landau.b_succ_lt
#print axioms LittlewoodInverse.Landau.b_antitone
#print axioms LittlewoodInverse.Landau.coeff_series
#print axioms LittlewoodInverse.Landau.series_differential
#print axioms LittlewoodInverse.Landau.square_series_differential
#print axioms LittlewoodInverse.Landau.coeff_square_series
#print axioms LittlewoodInverse.Landau.coefficient_convolution
#print axioms LittlewoodInverse.Landau.completion_norm_le
#print axioms LittlewoodInverse.Landau.twoSidedSum_continuous
#print axioms LittlewoodInverse.Landau.dirichlet_continuous
#print axioms LittlewoodInverse.Landau.dirichlet_norm_le
#print axioms LittlewoodInverse.Landau.completionError_integrable
#print axioms LittlewoodInverse.Landau.completionError_small
#print axioms LittlewoodInverse.Landau.twoSidedSum_model_error
#print axioms LittlewoodInverse.Landau.completionError_large
#print axioms LittlewoodInverse.Landau.completionError_real_bound
#print axioms LittlewoodInverse.Landau.fourier_neg_argument
#print axioms LittlewoodInverse.Landau.dirichlet_neg_argument
#print axioms LittlewoodInverse.Landau.polynomial_neg_argument
#print axioms LittlewoodInverse.Landau.extremizer_neg_argument
#print axioms LittlewoodInverse.Landau.twoSidedSum_neg_argument
#print axioms LittlewoodInverse.Landau.phase_conj
#print axioms LittlewoodInverse.Landau.completionError_even
#print axioms LittlewoodInverse.Landau.completionError_half_integrable
#print axioms LittlewoodInverse.Landau.completionError_integral_le
#print axioms LittlewoodInverse.Landau.completion_pairing_lower
#print axioms LittlewoodInverse.Landau.circle_even_integral
#print axioms LittlewoodInverse.Landau.model_norm
#print axioms LittlewoodInverse.Landau.conj_model
#print axioms LittlewoodInverse.Landau.model_identity
#print axioms LittlewoodInverse.Landau.fourier_distance_lower
#print axioms LittlewoodInverse.Landau.dirichlet_eq_fourierPolynomial
#print axioms LittlewoodInverse.Landau.completion_pairing_upper
#print axioms LittlewoodInverse.Landau.completion_pairing_lower_norm
#print axioms LittlewoodInverse.Landau.completion_log_asymptotic
#print axioms LittlewoodInverse.Landau.polynomial_eval
#print axioms LittlewoodInverse.Landau.polynomial_eval_succ
#print axioms LittlewoodInverse.Landau.polynomial_boundary_identity
#print axioms LittlewoodInverse.Landau.polynomial_boundary_weights
#print axioms LittlewoodInverse.Landau.re_lt_one_of_norm_le_one
#print axioms LittlewoodInverse.Landau.polynomial_ne_zero_closedDisk
#print axioms LittlewoodInverse.Landau.polynomial_quotient_spectrum
#print axioms LittlewoodInverse.Landau.reversePolynomial_evalCircle
#print axioms LittlewoodInverse.Landau.evalCircle_polynomial_ne_zero
#print axioms LittlewoodInverse.Landau.extremizer_continuous
#print axioms LittlewoodInverse.Landau.extremizer_norm
#print axioms LittlewoodInverse.Landau.extremizer_support
#print axioms LittlewoodInverse.Landau.extremizer_attains
#print axioms LittlewoodInverse.Landau.polynomial_coeff
#print axioms LittlewoodInverse.Landau.polynomial_square_coeff
#print axioms LittlewoodInverse.Landau.evalCircle_expansion
#print axioms LittlewoodInverse.Landau.evalCircle_continuous
#print axioms LittlewoodInverse.Landau.circlePairing_evalCircle
#print axioms LittlewoodInverse.Landau.circleFourierCoeff_evalCircle
#print axioms LittlewoodInverse.Landau.integral_norm_sq_evalCircle
#print axioms LittlewoodInverse.Landau.integral_norm_sq_polynomial
#print axioms LittlewoodInverse.Landau.pairing_square_eq_dirichlet
#print axioms LittlewoodInverse.Landau.spectral_bound
#print axioms LittlewoodInverse.block_cover_of_height_bounds
#print axioms LittlewoodInverse.long_block_almost_cover
#print axioms LittlewoodInverse.signed_slab_of_spectral_budget
#print axioms LittlewoodInverse.long_block_signed_progressions
#print axioms LittlewoodInverse.weightedPolynomial_sorted_ones
#print axioms LittlewoodInverse.sum_fin_reciprocal_eq_harmonic
#print axioms LittlewoodInverse.mps_logarithmic
#print axioms LittlewoodInverse.mpsConstant_pos
#print axioms LittlewoodInverse.mpsConstant_log_le
#print axioms LittlewoodInverse.macroscopic_hereditary_energy
#print axioms LittlewoodInverse.Majority.sum_singleton_coefficients
#print axioms LittlewoodInverse.Majority.exists_higher_correlation
#print axioms LittlewoodInverse.Majority.abs_finset_prod_le_one
#print axioms LittlewoodInverse.Majority.exists_higher_integral
#print axioms LittlewoodInverse.Majority.mixedMonomial_map
#print axioms LittlewoodInverse.Majority.every_block_contains_good_set
#print axioms LittlewoodInverse.Majority.majorityDegree_odd
#print axioms LittlewoodInverse.Majority.majorityDegree_lower
#print axioms LittlewoodInverse.Majority.majorityDegree_upper
#print axioms LittlewoodInverse.Majority.majorityDegree_le_sixty_six
#print axioms LittlewoodInverse.Majority.majorityDegree_minimal
#print axioms LittlewoodInverse.Majority.majority_correlation_threshold
#print axioms LittlewoodInverse.Majority.majority_density_denominator
#print axioms LittlewoodInverse.Majority.norm_circlePairing_le_integral_norm
#print axioms LittlewoodInverse.Majority.correlation_ratio_ge_one
#print axioms LittlewoodInverse.MajorityCounting.density_of_incidence
#print axioms LittlewoodInverse.MajorityCounting.goodFamily_fiber
#print axioms LittlewoodInverse.MajorityCounting.good_incidence_lower
#print axioms LittlewoodInverse.MajorityCounting.exists_dense_good_size
#print axioms LittlewoodInverse.MajorityCounting.factorial_ratio_ge_exp_neg
#print axioms LittlewoodInverse.MajorityCounting.descFactorial_ge_exp_neg
#print axioms LittlewoodInverse.MajorityCounting.split_factorial_ge
#print axioms LittlewoodInverse.MajorityCounting.ordered_density_lower
#print axioms LittlewoodInverse.MajorityCounting.tupleSupport_equiv
#print axioms LittlewoodInverse.MajorityCounting.validOrderedPair_append_injective
#print axioms LittlewoodInverse.MajorityCounting.orderedPairs_card_lower
#print axioms LittlewoodInverse.Majority.fourier_pow_nat
#print axioms LittlewoodInverse.Majority.phase_product_expansion
#print axioms LittlewoodInverse.Majority.phase_lift_expansion
#print axioms LittlewoodInverse.Majority.integral_phase_lift_expansion
#print axioms LittlewoodInverse.Majority.mixedMonomial_complement
#print axioms LittlewoodInverse.Majority.phase_selected_sums_conjugate
#print axioms LittlewoodInverse.Majority.integral_phase_balanced_identity
#print axioms LittlewoodInverse.Majority.integral_phase_pairing
#print axioms LittlewoodInverse.Majority.phaseTest_aestronglyMeasurable
#print axioms LittlewoodInverse.Majority.phaseTarget_integrable
#print axioms LittlewoodInverse.Majority.abs_phaseTest_le
#print axioms LittlewoodInverse.Majority.abs_phaseTarget_le
#print axioms LittlewoodInverse.Majority.integral_abs_phaseTarget_le
#print axioms LittlewoodInverse.Majority.phaseTest_ae_bound
#print axioms LittlewoodInverse.Majority.integral_phaseTarget_mul_phaseTest
#print axioms LittlewoodInverse.Majority.integral_phase_balanced_identity_real
#print axioms LittlewoodInverse.Majority.mixedMonomial_aestronglyMeasurable
#print axioms LittlewoodInverse.Majority.norm_mixedMonomial_le_one
#print axioms LittlewoodInverse.Majority.mixedMonomial_ae_bound
#print axioms LittlewoodInverse.Majority.mixed_pair_integrable
#print axioms LittlewoodInverse.Majority.integral_phase_balanced_pairings
#print axioms LittlewoodInverse.Majority.exists_balanced_pairing
#print axioms LittlewoodInverse.Majority.exists_balanced_higher_monomial
#print axioms LittlewoodInverse.Majority.exists_balanced_higher_monomial_of_ratio
#print axioms LittlewoodInverse.structural_inverse_of_terminal
#print axioms LittlewoodInverse.MomentCertificate.finite_error_bound
#print axioms LittlewoodInverse.MomentCounting.fourier_sum
#print axioms LittlewoodInverse.MomentCounting.polynomial_pow
#print axioms LittlewoodInverse.MomentCounting.norm_even_pow_expansion
#print axioms LittlewoodInverse.MomentCounting.integral_even_moment
#print axioms LittlewoodInverse.additiveEnergy_le_card_cube
#print axioms LittlewoodInverse.one_le_littlewoodNorm
#print axioms LittlewoodInverse.integral_norm_le_sqrt_integral_norm_sq
#print axioms LittlewoodInverse.littlewoodNorm_le_sqrt_card
#print axioms LittlewoodInverse.integral_norm_sq_fourierPolynomial_sub
#print axioms LittlewoodInverse.littlewoodNorm_sub_le_sqrt_symmDiff
#print axioms LittlewoodInverse.fourierPolynomial_translate
#print axioms LittlewoodInverse.littlewoodNorm_translate
#print axioms LittlewoodInverse.fourierPolynomial_dilate
#print axioms LittlewoodInverse.littlewoodNorm_dilate
#print axioms LittlewoodInverse.littlewoodNorm_affine
#print axioms LittlewoodInverse.NumericalConstant.tailError_upper
#print axioms LittlewoodInverse.NumericalConstant.littlewoodCoefficient_gt_decimal
#print axioms LittlewoodInverse.NumericalConstant.littlewoodCoefficient_gt_sharp_decimal
#print axioms LittlewoodInverse.OuterAlgebra.pairProducts_nonneg
#print axioms LittlewoodInverse.OuterAlgebra.pairProducts_eq_half
#print axioms LittlewoodInverse.OuterAlgebra.bonferroni_two
#print axioms LittlewoodInverse.OuterAlgebra.q_eq_one_sub_sq
#print axioms LittlewoodInverse.OuterAlgebra.q_mem_Icc
#print axioms LittlewoodInverse.OuterAlgebra.outer_update_bound
#print axioms LittlewoodInverse.OuterAlgebra.one_sub_exp_neg_le
#print axioms LittlewoodInverse.OuterAlgebra.whole_product_reduction
#print axioms LittlewoodInverse.OuterAlgebra.weighted_cauchy
#print axioms LittlewoodInverse.OuterAlgebra.coupled_tail
#print axioms LittlewoodInverse.OuterAlgebra.first_level_expansion
#print axioms LittlewoodInverse.OuterAlgebra.first_level_polynomial_majorant
#print axioms LittlewoodInverse.OuterAlgebra.first_level_coefficient_pos
#print axioms LittlewoodInverse.OuterAlgebra.first_tail_weight
#print axioms LittlewoodInverse.OuterAlgebra.second_tail_weight
#print axioms LittlewoodInverse.OuterAlgebra.tail_constant_algebra
#print axioms LittlewoodInverse.OuterAlgebra.finite_geometric_weights
#print axioms LittlewoodInverse.OuterAlgebra.finite_weight_budget
#print axioms LittlewoodInverse.OuterAlgebra.higher_tail_weight_lower
#print axioms LittlewoodInverse.OuterAlgebra.convex_endpoint_majorant
#print axioms LittlewoodInverse.OuterAlgebra.log_ten_lt_five_halves
#print axioms LittlewoodInverse.OuterAlgebra.scalar_endpoint_negative
#print axioms LittlewoodInverse.OuterAlgebra.log_nine_upper
#print axioms LittlewoodInverse.OuterAlgebra.coefficient_gt_decimal
#print axioms LittlewoodInverse.circleFourierCoeff_eq_fourierCoeff
#print axioms LittlewoodInverse.circleFourierCoeff_conj
#print axioms LittlewoodInverse.hasSum_conj_circleFourierCoeff_mul
#print axioms LittlewoodInverse.circleFourierCoeff_zero
#print axioms LittlewoodInverse.integral_mul_of_nonpositive_support
#print axioms LittlewoodInverse.circleFourierCoeff_mul_fourier
#print axioms LittlewoodInverse.memLp_mul_fourier
#print axioms LittlewoodInverse.nonpositive_support_mul
#print axioms LittlewoodInverse.memLp_finset_prod_top
#print axioms LittlewoodInverse.finite_product_nonpositive_support_mean
#print axioms LittlewoodInverse.schwarzIntegral_zero
#print axioms LittlewoodInverse.exists_nonpositive_outer_of_log
#print axioms LittlewoodInverse.outer_damping
#print axioms LittlewoodInverse.finite_product_mean_eq_prod_zeroCoeff
#print axioms LittlewoodInverse.norm_fourierPolynomial_le_card
#print axioms LittlewoodInverse.outer_damping_fourierPolynomial
#print axioms LittlewoodInverse.outer_update_bound
#print axioms LittlewoodInverse.normalizedPolynomial_upperSpectrum
#print axioms LittlewoodInverse.interval_subset_upperSpectrum
#print axioms LittlewoodInverse.upperSpectrum_mul
#print axioms LittlewoodInverse.dampedTest_upperSpectrum
#print axioms LittlewoodInverse.damped_interval_endpoint
#print axioms LittlewoodInverse.outer_interval_endpoint
#print axioms LittlewoodInverse.outer_interval_log_endpoint
#print axioms LittlewoodInverse.exists_dampingData
#print axioms LittlewoodInverse.DenseBlocks.certificateBudget_ge_one
#print axioms LittlewoodInverse.DenseBlocks.uniform_certificate_budget
#print axioms LittlewoodInverse.circleFourierCoeff_modulate
#print axioms LittlewoodInverse.DenseBlocks.certificate_continuous
#print axioms LittlewoodInverse.DenseBlocks.certificate_norm_le
#print axioms LittlewoodInverse.DenseBlocks.certificate_coeff
#print axioms LittlewoodInverse.DenseBlocks.other_block_coeff_zero
#print axioms LittlewoodInverse.DenseBlocks.certificate_pairing
#print axioms LittlewoodInverse.PacketEnergy.integral_cube_mul_fourth_le
#print axioms LittlewoodInverse.PacketEnergy.fourier_cube_mul_fourth_le
#print axioms LittlewoodInverse.PacketEnergy.highmoment_le
#print axioms LittlewoodInverse.PacketEnergy.highmoment_fourth_le
#print axioms LittlewoodInverse.PacketEnergy.shifted_relation_integral
#print axioms LittlewoodInverse.PacketEnergy.shifted_relation_le_highmoment
#print axioms LittlewoodInverse.PacketEnergy.shifted_relation_energy_bound
#print axioms LittlewoodInverse.PacketEnergy.shifted_relations_fourth_bound
#print axioms LittlewoodInverse.PacketEnergy.energy_from_shifted_relations
#print axioms LittlewoodInverse.PacketEnergy.carryRange_nonempty
#print axioms LittlewoodInverse.PacketEnergy.carryRange_card
#print axioms LittlewoodInverse.PacketEnergy.exponential_carry_bound
#print axioms LittlewoodInverse.PacketEnergy.exponential_energy_from_relations
#print axioms LittlewoodInverse.PacketEnergy.exponential_energy_small_set
#print axioms LittlewoodInverse.DenseBlocks.translated_disjoint
#print axioms LittlewoodInverse.DenseBlocks.card_eq_sum
#print axioms LittlewoodInverse.DenseBlocks.block_card_upper
#print axioms LittlewoodInverse.DenseBlocks.card_lower
#print axioms LittlewoodInverse.DenseBlocks.card_upper
#print axioms LittlewoodInverse.DenseBlocks.card_upper_density
#print axioms LittlewoodInverse.DenseBlocks.labels_card
#print axioms LittlewoodInverse.DenseBlocks.label_image_indexSet
#print axioms LittlewoodInverse.DenseBlocks.indexSet_card
#print axioms LittlewoodInverse.DenseBlocks.labelLift_card_eq
#print axioms LittlewoodInverse.DenseBlocks.labelLift_card_lower
#print axioms LittlewoodInverse.DenseBlocks.labelLift_card_upper
#print axioms LittlewoodInverse.DenseBlocks.labelLift_subset
#print axioms LittlewoodInverse.DenseBlocks.labelLift_disjoint
#print axioms LittlewoodInverse.DenseBlocks.labelLift_representation
#print axioms LittlewoodInverse.DenseBlocks.labelLift_sumset_card
#print axioms LittlewoodInverse.DenseBlocks.mem_labelLift
#print axioms LittlewoodInverse.DenseBlocks.labelLift_labels
#print axioms LittlewoodInverse.DenseBlocks.labelLift_sdiff
#print axioms LittlewoodInverse.DenseBlocks.labelLift_biUnion
#print axioms LittlewoodInverse.DenseBlocks.almostCover_of_labels
#print axioms LittlewoodInverse.PacketEnergy.shiftedRelations_card
#print axioms LittlewoodInverse.PacketEnergy.ordered_count_le_relations
#print axioms LittlewoodInverse.DenseBlocks.balanced_pairing_label_witness_reindex
#print axioms LittlewoodInverse.DenseBlocks.label_hereditary_energy
#print axioms LittlewoodInverse.circleFourierCoeff_mul_eq_tsum
#print axioms LittlewoodInverse.spectrumIn_mul
#print axioms LittlewoodInverse.spectrumIn_conj
#print axioms LittlewoodInverse.spectrumIn_one
#print axioms LittlewoodInverse.spectrumIn_prod
#print axioms LittlewoodInverse.finset_floor_error
#print axioms LittlewoodInverse.bounded_finset_floor_carry
#print axioms LittlewoodInverse.DenseBlocks.certificate_spectrum
#print axioms LittlewoodInverse.DenseBlocks.certificate_memLp
#print axioms LittlewoodInverse.DenseBlocks.balancedCertificate_continuous
#print axioms LittlewoodInverse.DenseBlocks.balancedCertificate_spectrum
#print axioms LittlewoodInverse.DenseBlocks.balanced_pairing_witness
#print axioms LittlewoodInverse.DenseBlocks.balanced_pairing_label_witness
#print axioms LittlewoodInverse.interlacedSet_energy_size_cost
#print axioms LittlewoodInverse.interlacedSet_doubling_cost
#print axioms LittlewoodInverse.interlacedSet_low_norm
#print axioms LittlewoodInverse.prefix_coefficient_obstruction
#print axioms LittlewoodInverse.initial_segment_parameter_obstruction
#print axioms LittlewoodInverse.prefix_threshold_eventually_ge_fibres
#print axioms LittlewoodInverse.finite_peeling
#print axioms LittlewoodInverse.disjoint_block_count
#print axioms LittlewoodInverse.hereditary_energy_cover
#print axioms LittlewoodInverse.hereditary_energy_cover_polynomial
#print axioms LittlewoodInverse.continuous_intervalIntegrable_div_id
#print axioms LittlewoodInverse.periodic_integral_upto_le
#print axioms LittlewoodInverse.periodic_harmonic_lower
#print axioms LittlewoodInverse.integral_scaled_div_id
#print axioms LittlewoodInverse.periodic_scaled_integral_le
#print axioms LittlewoodInverse.periodic_harmonic_upper
#print axioms LittlewoodInverse.periodic_harmonic_error
#print axioms LittlewoodInverse.eventually_log_square_small
#print axioms LittlewoodInverse.exceptional_perturbation_inverse
#print axioms LittlewoodInverse.card_sdiff_le_symmDiff
#print axioms LittlewoodInverse.card_le_card_add_symmDiff
#print axioms LittlewoodInverse.almostCover_intersect
#print axioms LittlewoodInverse.PhaseNormalization.phase_zero
#print axioms LittlewoodInverse.PhaseNormalization.norm_phase_le_one
#print axioms LittlewoodInverse.PhaseNormalization.norm_phase_eq_one
#print axioms LittlewoodInverse.PhaseNormalization.norm_mul_phase
#print axioms LittlewoodInverse.PhaseNormalization.phase_perturbation_weighted
#print axioms LittlewoodInverse.PhaseNormalization.phase_perturbation
#print axioms LittlewoodInverse.PhaseNormalization.phase_difference_le_two
#print axioms LittlewoodInverse.PhaseNormalization.self_pair
#print axioms LittlewoodInverse.PhaseNormalization.pairing_loss_le
#print axioms LittlewoodInverse.PhaseNormalization.phase_aestronglyMeasurable
#print axioms LittlewoodInverse.PhaseNormalization.phase_pair_integrable
#print axioms LittlewoodInverse.PhaseNormalization.weighted_phase_error_integrable
#print axioms LittlewoodInverse.PhaseNormalization.integral_pairing_loss_le
#print axioms LittlewoodInverse.PhaseNormalization.phase_positive_mul
#print axioms LittlewoodInverse.PhaseNormalization.pairing_loss_le_model
#print axioms LittlewoodInverse.PhaseNormalization.quotient_conj_eq_phase_sq
#print axioms LittlewoodInverse.PhaseNormalization.quotient_conj_norm_le
#print axioms LittlewoodInverse.PhaseNormalization.quotient_conj_perturbation
#print axioms LittlewoodInverse.PhaseNormalization.small_arc_integral
#print axioms LittlewoodInverse.PhaseNormalization.large_arc_integrable
#print axioms LittlewoodInverse.PhaseNormalization.large_arc_integral
#print axioms LittlewoodInverse.PhaseNormalization.two_arc_error_bound
#print axioms LittlewoodInverse.PhaseNormalization.finite_two_arc_error_bound
#print axioms LittlewoodInverse.fourierPolynomial_norm_le_card
#print axioms LittlewoodInverse.freiman_even_polynomial_integral
#print axioms LittlewoodInverse.freiman_norm_transport_of_approximation
#print axioms LittlewoodInverse.dampingTail_eq_reindexed
#print axioms LittlewoodInverse.initial_segment_pairing_uniform
#print axioms LittlewoodInverse.geometric_prefix_lower_bound
#print axioms LittlewoodInverse.PrefixCounting.relation_card
#print axioms LittlewoodInverse.PrefixCounting.ordered_count_filter
#print axioms LittlewoodInverse.PrefixCounting.reflected_count
#print axioms LittlewoodInverse.PrefixCounting.diagonal_count
#print axioms LittlewoodInverse.PrefixCounting.ordered_collision_identity
#print axioms LittlewoodInverse.indexedFourierSum_continuous
#print axioms LittlewoodInverse.indexedFourierSum_second_moment
#print axioms LittlewoodInverse.integrable_mul_fourier
#print axioms LittlewoodInverse.circlePairing_fourier_mul
#print axioms LittlewoodInverse.circlePairing_fourierPolynomial_mul
#print axioms LittlewoodInverse.initial_segment_pairing_localization
#print axioms LittlewoodInverse.prefixKernel_continuous
#print axioms LittlewoodInverse.prefixKernel_second_moment
#print axioms LittlewoodInverse.integrable_fourier_mul_star
#print axioms LittlewoodInverse.circlePairing_indexedFourierSum
#print axioms LittlewoodInverse.pairing_eq_prefixKernel
#print axioms LittlewoodInverse.prefixKernel_integral
#print axioms LittlewoodInverse.circlePairing_cauchy_schwarz_sq
#print axioms LittlewoodInverse.prefix_pairing_error_identity
#print axioms LittlewoodInverse.initial_segment_pairing_error_sq
#print axioms LittlewoodInverse.circlePairing_div_nat_right
#print axioms LittlewoodInverse.initial_segment_pairing_error
#print axioms LittlewoodInverse.almostCover_of_macroscopic_energy
#print axioms LittlewoodInverse.uniformAlmostCovers_implies_energy
#print axioms LittlewoodInverse.uniformMacroscopicEnergy_implies_cover
#print axioms LittlewoodInverse.uniform_cover_iff_macroscopic_energy
#print axioms LittlewoodInverse.littlewood_asymptotic
#print axioms LittlewoodInverse.sincMoment_nat_pos
#print axioms LittlewoodInverse.momentCoefficient_pos
#print axioms LittlewoodInverse.Landau.b_sq_asymptotic_error
#print axioms LittlewoodInverse.quantitative_theorem
#print axioms LittlewoodInverse.modelMap_freiman
#print axioms LittlewoodInverse.modelMap_image
#print axioms LittlewoodInverse.models_card
#print axioms LittlewoodInverse.repeated_model_norm_transport
#print axioms LittlewoodInverse.fibre_norm_le
#print axioms LittlewoodInverse.residue_reconstruction
#print axioms LittlewoodInverse.affineImage_residueChild
#print axioms LittlewoodInverse.fibreUnion_residueChild
#print axioms LittlewoodInverse.residue_projection_norm_le
#print axioms LittlewoodInverse.assembly_retained_leaves
#print axioms LittlewoodInverse.ScalarCoupling.hasSum_logRemainder
#print axioms LittlewoodInverse.ScalarCoupling.logRemainder_mul_le
#print axioms LittlewoodInverse.ScalarCoupling.h_eq_remainder
#print axioms LittlewoodInverse.ScalarCoupling.h_cubic_majorant
#print axioms LittlewoodInverse.ScalarCoupling.scalar_large_b_pointwise
#print axioms LittlewoodInverse.ScalarCoupling.normalizedMagnitude_continuous
#print axioms LittlewoodInverse.ScalarCoupling.normalizedMagnitude_nonneg
#print axioms LittlewoodInverse.ScalarCoupling.normalizedMagnitude_le_one
#print axioms LittlewoodInverse.ScalarCoupling.normalized_second_moment
#print axioms LittlewoodInverse.ScalarCoupling.normalized_moment_le_one
#print axioms LittlewoodInverse.ScalarCoupling.scalar_large_b_integral
#print axioms LittlewoodInverse.ScalarCoupling.hasSum_tailFromFive
#print axioms LittlewoodInverse.ScalarCoupling.tailFromFive_eq_tsum
#print axioms LittlewoodInverse.ScalarCoupling.first_level_exact
#print axioms LittlewoodInverse.ScalarCoupling.first_level_pointwise_tail
#print axioms LittlewoodInverse.ScalarCoupling.first_level_pointwise
#print axioms LittlewoodInverse.ScalarCoupling.hasSum_integral_tail
#print axioms LittlewoodInverse.ScalarCoupling.normalized_integral_tail_eq_tsum
#print axioms LittlewoodInverse.ScalarCoupling.first_level_integral
#print axioms LittlewoodInverse.SeriesCertificate.summable_momentSeries
#print axioms LittlewoodInverse.SeriesCertificate.momentSeries_le_finite
#print axioms LittlewoodInverse.SeriesCertificate.tailError_eq_momentSeries
#print axioms LittlewoodInverse.SeriesCertificate.tailError_eq_delta
#print axioms LittlewoodInverse.SeriesCertificate.tailError_nonneg
#print axioms LittlewoodInverse.SharpLogBounds.log_nine_upper
#print axioms LittlewoodInverse.SharpLogBounds.log_ten_upper
#print axioms LittlewoodInverse.SharpLogBounds.endpoint_sharp_upper
#print axioms LittlewoodInverse.SharpLogBounds.coefficient_gt_sharp_decimal
#print axioms LittlewoodInverse.complex_pointwise_excess
#print axioms LittlewoodInverse.sidon_bernoulli_twenty
#print axioms LittlewoodInverse.sidon_small_denominator
#print axioms LittlewoodInverse.sidon_small_variance
#print axioms LittlewoodInverse.sidon_large_variance
#print axioms LittlewoodInverse.sidon_large_variance_sqrt
#print axioms LittlewoodInverse.sidon_twentieth_from_scalar_bounds
#print axioms LittlewoodInverse.coefficient_twentieth_le_square
#print axioms LittlewoodInverse.sidon_excess_gram
#print axioms LittlewoodInverse.sidon_imaginary_second_moment
#print axioms LittlewoodInverse.sidon_third_moment
#print axioms LittlewoodInverse.sidon_small_t_analytic
#print axioms LittlewoodInverse.integral_L1_sq_ge_half_L2
#print axioms LittlewoodInverse.sidon_shifted_second_moment
#print axioms LittlewoodInverse.sidon_twentieth_analytic
#print axioms LittlewoodInverse.sidon_fibre_energy_bound
#print axioms LittlewoodInverse.ternary_power_strictMono
#print axioms LittlewoodInverse.ternary_sum_sorted
#print axioms LittlewoodInverse.ternary_powers_sidon
#print axioms LittlewoodInverse.ternary_pow_lt
#print axioms LittlewoodInverse.ternary_pair_sum_lt
#print axioms LittlewoodInverse.ternaryResidues_card
#print axioms LittlewoodInverse.ternaryResidues_sidon
#print axioms LittlewoodInverse.uniform_fibre_norm_upper
#print axioms LittlewoodInverse.uniform_fibre_card
#print axioms LittlewoodInverse.interlacedSet_card
#print axioms LittlewoodInverse.integerInterval_card
#print axioms LittlewoodInverse.interlacedSet_norm
#print axioms LittlewoodInverse.uniform_fibre_energy
#print axioms LittlewoodInverse.interlacedSet_energy
#print axioms LittlewoodInverse.interval_as_blockInflation
#print axioms LittlewoodInverse.interval_terminal
#print axioms LittlewoodInverse.interlacedSet_assembly
#print axioms LittlewoodInverse.uniform_fibre_prefix_layers
#print axioms LittlewoodInverse.uniform_fibre_prefix_energy
#print axioms LittlewoodInverse.interlacedSet_prefix_energy
#print axioms LittlewoodInverse.sidon_fibres
#print axioms LittlewoodInverse.interlacedSet_individual_fibre
#print axioms LittlewoodInverse.FiniteSetPartition.sum_indicator
#print axioms LittlewoodInverse.signed_progression_glue_bound
#print axioms LittlewoodInverse.normalized_interval_moment_eq_scaledSinc
#print axioms LittlewoodInverse.SincFormula.normalizedMoment_interval_eq_relationCount
#print axioms LittlewoodInverse.SincFormula.normalizedMoment_interval_binomial
#print axioms LittlewoodInverse.SincFormula.sincMoment_even_eq_sum
#print axioms LittlewoodInverse.SincFormula.sincMoment_even_formula
#print axioms LittlewoodInverse.SincFormula.sincMoment_even_eq_rat
#print axioms LittlewoodInverse.SincMoments.abs_sinc_ge_two_div_pi
#print axioms LittlewoodInverse.SincMoments.abs_mul_abs_sinc_le
#print axioms LittlewoodInverse.SincMoments.scaledSincKernel_bounds
#print axioms LittlewoodInverse.SincMoments.scaledSincKernel_power_bound
#print axioms LittlewoodInverse.SincMoments.scaledSincKernel_measurable
#print axioms LittlewoodInverse.SincMoments.tendsto_scaledSincKernel
#print axioms LittlewoodInverse.SincMoments.sinc_power_bound
#print axioms LittlewoodInverse.SincMoments.integrable_sinc_power
#print axioms LittlewoodInverse.SincMoments.tendsto_integral_scaledSincKernel
#print axioms LittlewoodInverse.sine_hasDerivAt
#print axioms LittlewoodInverse.cosine_hasDerivAt
#print axioms LittlewoodInverse.fourierCoeffOn_sine
#print axioms LittlewoodInverse.fourierCoeff_periodicSine
#print axioms LittlewoodInverse.sineWeight_nonneg
#print axioms LittlewoodInverse.sineWeight_telescope
#print axioms LittlewoodInverse.sum_sineWeight
#print axioms LittlewoodInverse.hasSum_sineWeight_tail
#print axioms LittlewoodInverse.summable_fourierCoeff_periodicSine
#print axioms LittlewoodInverse.fourier_real_part
#print axioms LittlewoodInverse.sine_fourier_term_real
#print axioms LittlewoodInverse.hasSum_sine_cosine
#print axioms LittlewoodInverse.sine_cosine_truncation_error
#print axioms LittlewoodInverse.cyclic_spectral_almost_cover
#print axioms LittlewoodInverse.mem_arithmeticSlab_residueHeight
#print axioms LittlewoodInverse.arithmeticSlab_subset
#print axioms LittlewoodInverse.arithmeticSlab_nonempty
#print axioms LittlewoodInverse.arithmeticSlab_disjoint
#print axioms LittlewoodInverse.arithmeticSlab_sdiff_union
#print axioms LittlewoodInverse.arithmeticSlab_almost_cover
#print axioms LittlewoodInverse.uniform_slab_cover
#print axioms LittlewoodInverse.integral_gram_sq_le
#print axioms LittlewoodInverse.integral_cauchy_schwarz_sq
#print axioms LittlewoodInverse.integral_weighted_cauchy_schwarz_sq
#print axioms LittlewoodInverse.complex_pairing_fourth_le
#print axioms LittlewoodInverse.complex_spectral_hereditary
#print axioms LittlewoodInverse.spectral_hereditary_energy
#print axioms LittlewoodInverse.card_fourth_le_norm_sq_card_energy
#print axioms LittlewoodInverse.SymmetricChains.wideDecode_rank
#print axioms LittlewoodInverse.SymmetricChains.wideDecode_index
#print axioms LittlewoodInverse.SymmetricChains.wideDecode_encode
#print axioms LittlewoodInverse.SymmetricChains.wideEncode_decode
#print axioms LittlewoodInverse.SymmetricChains.wideDecode_monotone
#print axioms LittlewoodInverse.SymmetricChains.gridRank_strictMono
#print axioms LittlewoodInverse.SymmetricChains.Decomposition.middlePoint_rank
#print axioms LittlewoodInverse.SymmetricChains.Decomposition.comparable_of_same_index
#print axioms LittlewoodInverse.SymmetricChains.Decomposition.antichain_card_le_middle
#print axioms LittlewoodInverse.SymmetricChains.grid_antichain_card_le_middle
#print axioms LittlewoodInverse.SymmetricChains.nonempty_grid_antichain_card_le_middle
#print axioms LittlewoodInverse.SymmetricChains.Decomposition.covBy_of_adjacent
#print axioms LittlewoodInverse.SymmetricChains.grid_chains_saturated
#print axioms LittlewoodInverse.SymmetricChains.grid_rank_card_le_middle
#print axioms LittlewoodInverse.integral_mul_le_sqrt_moments
#print axioms LittlewoodInverse.integral_sum_sq_le
#print axioms LittlewoodInverse.integral_crossTerm_le
#print axioms LittlewoodInverse.coupled_whole_product
#print axioms LittlewoodInverse.outer_product_coupled
#print axioms LittlewoodInverse.TailWeights.v_pos
#print axioms LittlewoodInverse.TailWeights.b_zero
#print axioms LittlewoodInverse.TailWeights.b_ge
#print axioms LittlewoodInverse.TailWeights.v_sum
#print axioms LittlewoodInverse.TailWeights.weighted_constant
#print axioms LittlewoodInverse.TailWeights.constant_sum
#print axioms LittlewoodInverse.TailWeights.delta_nonneg
#print axioms LittlewoodInverse.TailWeights.tailError_eq
#print axioms LittlewoodInverse.TailWeights.finite_budget
#print axioms LittlewoodInverse.uniform_terminal_cover
#print axioms LittlewoodInverse.structural_inverse_theorem
#print axioms LittlewoodInverse.BudgetTree.leafPowerSum_le_rootBudget
#print axioms LittlewoodInverse.BudgetTree.leafCount_le_leafPowerSum
#print axioms LittlewoodInverse.BudgetTree.leaf_twentieth_budget
#print axioms LittlewoodInverse.BudgetTree.leafCount_le_rootBudget
#print axioms LittlewoodInverse.ternaryExceptions_card
#print axioms LittlewoodInverse.unbalancedSet_disjoint
#print axioms LittlewoodInverse.unbalancedSet_card
#print axioms LittlewoodInverse.littlewoodNorm_disjoint_union
#print axioms LittlewoodInverse.unbalancedSet_norm
#print axioms LittlewoodInverse.ternaryExceptions_succ
#print axioms LittlewoodInverse.unbalancedSet_zero
#print axioms LittlewoodInverse.unbalancedSet_succ
#print axioms LittlewoodInverse.zero_one_sidon
#print axioms LittlewoodInverse.zero_one_fibre_union
#print axioms LittlewoodInverse.unbalancedSet_fibre_recursion
#print axioms LittlewoodInverse.unbalancedSet_nonempty
#print axioms LittlewoodInverse.unbalancedSet_assembly
#print axioms LittlewoodInverse.ternaryDigitSet_card
#print axioms LittlewoodInverse.ternaryDigitSet_assembly
#print axioms LittlewoodInverse.ternaryDigitSet_norm_twentieth
#print axioms LittlewoodInverse.ternaryDigitValue_cons
#print axioms LittlewoodInverse.ternaryDigitSet_mem
#print axioms LittlewoodInverse.ternaryDigitSet_eq
#print axioms LittlewoodInverse.ternaryDigitSet_norm_lower
#print axioms LittlewoodInverse.logarithmicChainDepth_sqrt
#print axioms LittlewoodInverse.logarithmic_chain_norm
#print axioms LittlewoodInverse.logarithmicChainDepth_tendsto
#print axioms LittlewoodInverse.logarithmic_chain_low_norm
#print axioms LittlewoodInverse.ternaryDigitSet_eventually_not_low_norm
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_nonneg
#print axioms LittlewoodInverse.UniformMoments.card_integerInterval
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_even_le_interval
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_odd_sq_le
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_odd_le_sqrt
#print axioms LittlewoodInverse.UniformMoments.tendsto_normalizedMoment_interval
#print axioms LittlewoodInverse.UniformMoments.tendsto_normalizedMoment_interval_even
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_even_uniform
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_odd_le_interval_sqrt
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_odd_uniform
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_uniform
#print axioms LittlewoodInverse.UniformMoments.sincMoment_nat_nonneg
#print axioms LittlewoodInverse.UniformMoments.sincMoment_nat_le_one
#print axioms LittlewoodInverse.UniformMoments.sincMoment_two
#print axioms LittlewoodInverse.UniformMoments.normalizedMoment_interval_four
#print axioms LittlewoodInverse.UniformMoments.sincMoment_four
#print axioms LittlewoodInverse.UniformMoments.momentCoefficient_nonneg
#print axioms LittlewoodInverse.UniformMoments.momentCoefficient_le_one
#print axioms LittlewoodInverse.uniform_outer_tail_budget
#print axioms LittlewoodInverse.WholeProduct.pointwise_bonferroni
#print axioms LittlewoodInverse.WholeProduct.product_modulus
#print axioms LittlewoodInverse.WholeProduct.norm_sub_one_sq
#print axioms LittlewoodInverse.WholeProduct.integral_error_identity
#print axioms LittlewoodInverse.WholeProduct.estimate
